name: CD
on:
  push:
    branches:
      - rustica

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src

      - name: Package
        run: |
          mkdir -p core dist/MoonGRES/nightly/
          mv src/* core
          tar -czf dist/MoonGRES/nightly/core.tar.gz core

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: [ package ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: core
          path: dist

      - name: Install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf << EOF
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = ${{ secrets.R2_ENDPOINT }}
          acl = public-read
          EOF

      - name: Upload to R2
        run: |
          rclone copy dist r2:${{ secrets.R2_BUCKET_NAME }} --progress
